### ISSUE TITLE
Error on RaspberryPi: Failed to build the maintenance page

### ISSUE THREAD

**Issue by jhanarato** [suttacentral/legacy-suttacentral#203]
Hey folks,

My dear sister bought me a RaspberryPi a few weeks ago. I decided to see if I could get SC up and running.

I started with the instructions [here](https://github.com/suttacentral/suttacentral/wiki/Developer-Setup-Guide) and got as far as step 7 - running the `invoke server` command. Everything worked until I got the following errors and stack trace:
```
[2017-03-28 10:14:37] INFO sc.textdata.build TIM is ready
Building IMM
Font family mapping matches no font file: NotoSansKR ({'name': 'Noto Sans KR', 'subset_languages': 'ko'})
Font family mapping matches no font file: lumen-thai (Lumen Thai)
Font family mapping matches no font file: NotoSerif ({'name': 'Noto Serif', 'subset_languages': '*'})
Font family mapping matches no font file: NotoSansCJKsc ({'name': 'Noto Sans SC', 'subset_languages': ['zh', 'lzh']})
Font family mapping matches no font file: SkolarPE ({'name': 'Skolar Sutta Web', 'subset_languages': '*'})
Font family mapping matches no font file: NotoSansJP ({'name': 'Noto Sans JP', 'subset_languages': 'jp'})
Font family mapping matches no font file: skolar-devanagari (Skolar Devanagari)
Font family mapping matches no font file: ko-pub-batang (Ko Pub Batang)
Font family mapping matches no font file: noto-sans ({'name': 'Noto Sans', 'subset_languages': '*'})
Font family mapping matches no font file: noto-sans-hebrew (Noto Sans Hebrew)
Font family mapping matches no font file: NotoSansCJKtc ({'name': 'Noto Sans TC', 'subset_languages': ['zh', 'lzh']})
Font family mapping matches no font file: SkolarSansPE ({'name': 'Skolar Sans', 'subset_languages': '*'})
Font family mapping matches no font file: NotoSansTibetan (Noto Sans Tibetan)
Could not build maitenance page
Traceback (most recent call last):
  File "/home/pi/suttacentral/sc/show.py", line 361, in <module>
    build_maitenance_page()
  File "/home/pi/suttacentral/sc/show.py", line 356, in build_maitenance_page
    html = GenericView('errors/maintenance', {}).render()
  File "/home/pi/suttacentral/sc/views.py", line 236, in render
    template = self.get_template()
  File "/home/pi/suttacentral/sc/views.py", line 163, in get_template
    return self.env.get_template(template_name)
  File "/home/pi/suttacentral/sc/views.py", line 146, in env
    return jinja2_environment()
  File "/home/pi/suttacentral/sc/views.py", line 44, in jinja2_environment
    __jinja2_environment = build_jinja2_environment()
  File "/home/pi/suttacentral/sc/views.py", line 55, in build_jinja2_environment
    env.assets_environment = assets.get_env()
  File "/home/pi/suttacentral/sc/assets.py", line 103, in get_env
    sc_data_scripts_file = get_js_datascripts_filename()
  File "/home/pi/suttacentral/sc/assets.py", line 184, in get_js_datascripts_filename
    tasks.jsdata.build(minify=True, quiet=True)
  File "/home/pi/.pyenv/versions/3.5.0/envs/suttacentral/lib/python3.5/site-packages/invoke/tasks.py", line 107, in __call__
    if not isinstance(args[0], Context):
IndexError: tuple index out of range
Failed to build the maitenace page, this indicates critical problems, exiting
```

Your assistance is most welcome. :-)

Ven. J.R.

**Comment by blake-sc** [comment]
Hmm, try running: `pip install --upgrade invoke`

**Comment by jhanarato** [comment]
Did that, got this:
```
(suttacentral) pi@raspberrypi:~/suttacentral $ pip install --upgrade invoke
Requirement already up-to-date: invoke in /home/pi/.pyenv/versions/3.5.0/envs/suttacentral/lib/python3.5/site-packages
You are using pip version 7.1.2, however version 9.0.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```
And the above problem persists.

**Comment by jhanarato** [comment]
I'll try and debug this myself.
